/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminSeoIndexRouteImport } from './routes/admin/seo/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminBuilderIndexRouteImport } from './routes/admin/builder/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminSeoKeywordsRouteImport } from './routes/admin/seo/keywords'
import { Route as AdminMediaUploadRouteImport } from './routes/admin/media/upload'
import { Route as AdminBuilderSlugRouteImport } from './routes/admin/builder/$slug'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as AdminBlogCommentsRouteImport } from './routes/admin/blog/comments'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin/blog/categories'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoIndexRoute = AdminSeoIndexRouteImport.update({
  id: '/admin/seo/',
  path: '/admin/seo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/admin/media/',
  path: '/admin/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderIndexRoute = AdminBuilderIndexRouteImport.update({
  id: '/admin/builder/',
  path: '/admin/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoKeywordsRoute = AdminSeoKeywordsRouteImport.update({
  id: '/admin/seo/keywords',
  path: '/admin/seo/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaUploadRoute = AdminMediaUploadRouteImport.update({
  id: '/admin/media/upload',
  path: '/admin/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderSlugRoute = AdminBuilderSlugRouteImport.update({
  id: '/admin/builder/$slug',
  path: '/admin/builder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogCommentsRoute = AdminBlogCommentsRouteImport.update({
  id: '/admin/blog/comments',
  path: '/admin/blog/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/admin/blog/categories',
  path: '/admin/blog/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
  '/admin/media/upload': typeof AdminMediaUploadRoute
  '/admin/seo/keywords': typeof AdminSeoKeywordsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/builder/': typeof AdminBuilderIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
  '/admin/media/upload': typeof AdminMediaUploadRoute
  '/admin/seo/keywords': typeof AdminSeoKeywordsRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/builder': typeof AdminBuilderIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/seo': typeof AdminSeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
  '/admin/media/upload': typeof AdminMediaUploadRoute
  '/admin/seo/keywords': typeof AdminSeoKeywordsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/builder/': typeof AdminBuilderIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin/leads'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/new'
    | '/admin/builder/$slug'
    | '/admin/media/upload'
    | '/admin/seo/keywords'
    | '/admin/blog/'
    | '/admin/builder/'
    | '/admin/media/'
    | '/admin/seo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin/leads'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/new'
    | '/admin/builder/$slug'
    | '/admin/media/upload'
    | '/admin/seo/keywords'
    | '/admin/blog'
    | '/admin/builder'
    | '/admin/media'
    | '/admin/seo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin/leads'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/new'
    | '/admin/builder/$slug'
    | '/admin/media/upload'
    | '/admin/seo/keywords'
    | '/admin/blog/'
    | '/admin/builder/'
    | '/admin/media/'
    | '/admin/seo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogCommentsRoute: typeof AdminBlogCommentsRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBuilderSlugRoute: typeof AdminBuilderSlugRoute
  AdminMediaUploadRoute: typeof AdminMediaUploadRoute
  AdminSeoKeywordsRoute: typeof AdminSeoKeywordsRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBuilderIndexRoute: typeof AdminBuilderIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSeoIndexRoute: typeof AdminSeoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/': {
      id: '/admin/seo/'
      path: '/admin/seo'
      fullPath: '/admin/seo/'
      preLoaderRoute: typeof AdminSeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/admin/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder/': {
      id: '/admin/builder/'
      path: '/admin/builder'
      fullPath: '/admin/builder/'
      preLoaderRoute: typeof AdminBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/keywords': {
      id: '/admin/seo/keywords'
      path: '/admin/seo/keywords'
      fullPath: '/admin/seo/keywords'
      preLoaderRoute: typeof AdminSeoKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media/upload': {
      id: '/admin/media/upload'
      path: '/admin/media/upload'
      fullPath: '/admin/media/upload'
      preLoaderRoute: typeof AdminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder/$slug': {
      id: '/admin/builder/$slug'
      path: '/admin/builder/$slug'
      fullPath: '/admin/builder/$slug'
      preLoaderRoute: typeof AdminBuilderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/comments': {
      id: '/admin/blog/comments'
      path: '/admin/blog/comments'
      fullPath: '/admin/blog/comments'
      preLoaderRoute: typeof AdminBlogCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/categories': {
      id: '/admin/blog/categories'
      path: '/admin/blog/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogCommentsRoute: AdminBlogCommentsRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBuilderSlugRoute: AdminBuilderSlugRoute,
  AdminMediaUploadRoute: AdminMediaUploadRoute,
  AdminSeoKeywordsRoute: AdminSeoKeywordsRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBuilderIndexRoute: AdminBuilderIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSeoIndexRoute: AdminSeoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
